# Generated by Django 2.1.3 on 2018-11-18 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20181108_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('78377ec4-43ee-425e-ad2f-593775eda5bd'), primary_key=True, serialize=False, unique=True),
        ),
    ]
