# Generated by Django 2.1.3 on 2018-11-25 09:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20181118_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cec837e4-768a-45e7-9432-550a36ef2243'), primary_key=True, serialize=False, unique=True),
        ),
    ]
