# Generated by Django 2.1.3 on 2018-11-25 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20181125_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d49c9fcf-b4b7-47be-941b-3994dc86e1e6'), primary_key=True, serialize=False, unique=True),
        ),
    ]
