# Generated by Django 2.1.3 on 2018-11-26 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20181125_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pic_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d5553642-ca12-4113-8221-1ccc9f06c911'), primary_key=True, serialize=False, unique=True),
        ),
    ]
