# Generated by Django 2.1.3 on 2018-11-26 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20181126_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8db65a86-01bf-4693-9bc4-eda3485c7c82'), primary_key=True, serialize=False, unique=True),
        ),
    ]
