# Generated by Django 2.1.3 on 2018-11-30 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20181130_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('454fff0c-c5c6-4a5d-a8bb-f76bc7266d12'), primary_key=True, serialize=False, unique=True),
        ),
    ]
