# Generated by Django 2.1.3 on 2018-11-07 21:09

from django.db import migrations, models
import django.db.models.deletion
import gameroom.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('af60e400-34a6-4c03-aa45-2d02a78ad7fd'), primary_key=True, serialize=False, unique=True)),
                ('room_number', models.IntegerField(default=gameroom.models.GameRoom.generate_room_number)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='player.Player')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='player.Player')),
            ],
        ),
    ]
