# Generated by Django 2.1.3 on 2018-11-08 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7809fd2a-66aa-4ce3-a524-a19b27795a98'), primary_key=True, serialize=False, unique=True),
        ),
    ]
