# Generated by Django 2.1.3 on 2018-11-18 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0002_auto_20181108_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='node_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='players',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('67a3db5f-aa72-4aeb-baa7-a8f40a1a66c8'), primary_key=True, serialize=False, unique=True),
        ),
    ]
