# Generated by Django 2.1.3 on 2018-11-25 09:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0003_auto_20181118_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b74981e3-842f-4217-afe5-bddea0f6a5af'), primary_key=True, serialize=False, unique=True),
        ),
    ]
