# Generated by Django 2.1.3 on 2018-11-25 14:53

from django.db import migrations, models
import gameroom.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0005_auto_20181125_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='room_number',
            field=models.CharField(default=gameroom.models.GameRoom.generate_room_number, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c75ebaaa-fe0c-4fb0-b100-79483d91024b'), primary_key=True, serialize=False, unique=True),
        ),
    ]
