# Generated by Django 2.1.3 on 2018-11-26 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0007_auto_20181125_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('755eb6ae-ca19-4efa-a9fc-e9da672d6436'), primary_key=True, serialize=False, unique=True),
        ),
    ]
