# Generated by Django 2.1.3 on 2018-11-26 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0008_auto_20181126_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3d7025ec-f34d-403f-aaef-e83929616317'), primary_key=True, serialize=False),
        ),
    ]
