# Generated by Django 2.1.3 on 2018-11-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0010_auto_20181126_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='status',
            field=models.CharField(default='not_started', max_length=20),
        ),
    ]
